var N = null;var sourcesIndex = {};
sourcesIndex["transmog"] = {"name":"","files":["lib.rs","test_util.rs"]};
sourcesIndex["transmog_async"] = {"name":"","files":["lib.rs","reader.rs","writer.rs"]};
sourcesIndex["transmog_bincode"] = {"name":"","files":["lib.rs"]};
sourcesIndex["transmog_cbor"] = {"name":"","files":["lib.rs"]};
sourcesIndex["transmog_json"] = {"name":"","files":["lib.rs"]};
sourcesIndex["transmog_pot"] = {"name":"","files":["lib.rs"]};
sourcesIndex["transmog_versions"] = {"name":"","files":["lib.rs"]};
sourcesIndex["xtask"] = {"name":"","files":["main.rs"]};
createSourceSidebar();
